# Locations of all WreckRepair anvils in the world
anvil-locations:

#WARNING: THERE COULD BE AN ISSUE IN THE FUTURE WHERE IF A PLAYER WITH NO PERMISSION TRIES TO BREAK
#         AN ANVIL, EVEN IF WORLDGUARD PREVENTS THEM FROM DOING SO, THE BLOCKBREAKEVENT STILL EXECUTES
#         AS IF THE ANVIL HAS BEEN BROKEN. LOOK INTO THIS AND RETURN BACK HERE.